version: '3.7'

services:
  app:
    image: 'abhipick/examapp:1.0.4'
    build:
      context: .
    container_name: exam-portal
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/exam
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      #Please comment if running Exam portal from intellij Windows.
      - LOGGING_FILE_PATH=/exam-app-logs
    volumes:
      - shared-logs:/exam-app-logs
    ports:
      - "8081:8081"

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=exam
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - "3307:3306"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/datasources.yml

  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - shared-logs:/mnt/logs
    command: "--config.file=/etc/promtail/promtail-config.yml"

  loki:
    image: grafana/loki:2.4.0
    container_name: loki
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    restart: unless-stopped
    command: "-config.file=/etc/loki/loki-config.yml"
    ports:
      - "3100:3100"
    depends_on:
      - promtail
volumes:
  shared-logs: